export type { EmblaOptionsType } from './components/Options'
export type { EmblaEventType } from './components/EventHandler'
export type { EmblaPluginType } from './components/Plugins'
export type { EmblaCarouselType } from './components/EmblaCarousel'
export { default } from './components/EmblaCarousel'
